---
- name: Перевірка наявності групи sudo
  group:
    name: sudo
    state: present

- name: Створення користувача teacher із паролем за замовчуванням
  user:
    name: teacher
    password: "{{ '12345678' | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Створення директорії для користувача student (якщо її немає)
  file:
    path: /home/student
    state: directory
    owner: ansible
    group: ansible
    mode: '0755'

- name: Створення файлу gradebook із номером варіанта N
  copy:
    dest: /home/student/gradebook
    content: "14839938\n"
    owner: ansible
    group: ansible
    mode: '0644'

- name: Дозволити вхід по SSH з паролем (для teacher та operator)
  lineinfile:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
  notify: Перезапуск SSH